..............F
======================================================================
FAIL: test_netflix_solve_3 (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 96, in test_netflix_solve_3
    self.assertEqual(w.getvalue(), "17300:\n1.1\n17307:\n4.9\nRMSE: 0.22\n")
AssertionError: '17300:\n1.1\n17307:\n4.9\nRMSE: 0.64\n' != '17300:\n1.1\n17307:\n4.9\nRMSE: 0.22\n'
  17300:
  1.1
  17307:
  4.9
- RMSE: 0.64
?         ^^
+ RMSE: 0.22
?         ^^


----------------------------------------------------------------------
Ran 15 tests in 55.050s

FAILED (failures=1)
(1, '17300', '1762631')
(5, '17307', '2208129')
